import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Copy, Download, CheckCircle, Lightbulb } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

interface SummaryDisplayProps {
  summary: string;
  keyPoints: string[];
  fileName?: string;
}

export const SummaryDisplay = ({ summary, keyPoints, fileName }: SummaryDisplayProps) => {
  const { toast } = useToast();

  const handleCopy = () => {
    const fullText = `📝 Summary\n\n${summary}\n\n💡 Key Insights\n\n${keyPoints.map((point, i) => `${i + 1}. ${point}`).join("\n")}`;
    navigator.clipboard.writeText(fullText);
    toast({
      title: "✓ Copied to clipboard",
      description: "Summary is ready to paste anywhere",
    });
  };

  const handleDownload = () => {
    const fullText = `AI Summary of ${fileName || "Your Document"}\n${"=".repeat(50)}\n\n📝 SUMMARY\n\n${summary}\n\n💡 KEY INSIGHTS\n\n${keyPoints.map((point, i) => `${i + 1}. ${point}`).join("\n\n")}\n\n${"=".repeat(50)}\nGenerated by AI Note Summarizer`;
    const blob = new Blob([fullText], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `summary-${fileName?.replace(/\.[^/.]+$/, "") || "document"}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast({
      title: "✓ Downloaded successfully",
      description: "Check your downloads folder",
    });
  };

  return (
    <div className="space-y-6 animate-slide-up">
      {/* Header with actions */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="h-10 w-10 rounded-full bg-gradient-to-r from-primary to-accent flex items-center justify-center">
            <CheckCircle className="h-5 w-5 text-white" />
          </div>
          <div>
            <h2 className="text-2xl font-bold text-foreground">Analysis Complete</h2>
            <p className="text-sm text-muted-foreground">
              {fileName ? `Summary of ${fileName}` : "Your text has been analyzed"}
            </p>
          </div>
        </div>
        <div className="flex gap-2">
          <Button 
            variant="outline" 
            size="sm" 
            onClick={handleCopy}
            className="hover:bg-primary/5 hover:border-primary transition-colors"
          >
            <Copy className="h-4 w-4 mr-2" />
            Copy
          </Button>
          <Button 
            variant="outline" 
            size="sm" 
            onClick={handleDownload}
            className="hover:bg-primary/5 hover:border-primary transition-colors"
          >
            <Download className="h-4 w-4 mr-2" />
            Download
          </Button>
        </div>
      </div>

      {/* Summary Card */}
      <Card className="p-8 bg-gradient-to-br from-card to-secondary/20 border-2 shadow-lg">
        <div className="space-y-6">
          {/* Summary Section */}
          <div>
            <div className="flex items-center gap-2 mb-4">
              <div className="h-8 w-1 bg-gradient-to-b from-primary to-accent rounded-full" />
              <h3 className="text-lg font-semibold text-foreground">
                Summary
              </h3>
            </div>
            <p className="text-foreground/90 leading-relaxed text-lg pl-4">
              {summary}
            </p>
          </div>

          {/* Key Points Section */}
          {keyPoints.length > 0 && (
            <div>
              <div className="flex items-center gap-2 mb-4">
                <div className="h-8 w-1 bg-gradient-to-b from-accent to-primary rounded-full" />
                <h3 className="text-lg font-semibold text-foreground flex items-center gap-2">
                  <Lightbulb className="h-5 w-5 text-accent" />
                  Key Insights
                </h3>
              </div>
              <div className="space-y-4 pl-4">
                {keyPoints.map((point, index) => (
                  <div 
                    key={index} 
                    className="flex gap-4 group hover:translate-x-1 transition-transform duration-200"
                  >
                    <div className="flex-shrink-0 flex items-start pt-1">
                      <div className="flex items-center justify-center w-8 h-8 rounded-lg bg-gradient-to-br from-primary/10 to-accent/10 group-hover:from-primary/20 group-hover:to-accent/20 transition-colors">
                        <span className="text-sm font-bold bg-gradient-to-r from-primary to-accent bg-clip-text text-transparent">
                          {index + 1}
                        </span>
                      </div>
                    </div>
                    <p className="text-foreground/90 leading-relaxed flex-1 pt-1">
                      {point}
                    </p>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      </Card>

      {/* Stats Footer */}
      <div className="flex items-center justify-center gap-6 text-sm text-muted-foreground">
        <div className="flex items-center gap-2">
          <div className="h-2 w-2 rounded-full bg-success animate-pulse" />
          <span>Powered by AI</span>
        </div>
        <div className="h-4 w-px bg-border" />
        <span>{keyPoints.length} key insights extracted</span>
      </div>
    </div>
  );
};
